updated docker file for permission

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -5,10 +5,12 @@ MAINTAINER "Praveen Kumar Addakula"
 USER smrtanalysis
 ENV SMRT_ROOT=/opt/pacbio/smrtlink
 
-# Ensure the file has the right permissions before adding it
+# Ensure the file has the right permissions and ownership before adding it
 COPY services-status /opt/pacbio/smrtlink/admin/bin/services-status
-RUN chmod +x /opt/pacbio/smrtlink/admin/bin/services-status || echo "Permission change failed, ignoring"
+
+# Change ownership to smrtanalysis user and then make the file executable
+RUN chown smrtanalysis:smrtanalysis /opt/pacbio/smrtlink/admin/bin/services-status \
+    && chmod +x /opt/pacbio/smrtlink/admin/bin/services-status || echo "Permission change failed, ignoring"
 
 EXPOSE 22 8243 9243 9443
 ENTRYPOINT ["/opt/pacbio/smrtlink/admin/bin/services-start"]
-
